In [1]:
import pandas as pd
import os
path=input('輸入路徑:')
VLRROBA_list=pd.DataFrame(columns=['A'])
for i in os.listdir(r"{}".format(path)):#組合所有excel
    df=pd.read_excel(r"{}\{}".format(path,i))
    VLRROBA_list=pd.concat([df,VLRROBA_list],axis=0)
VLRROBA_list=VLRROBA_list.drop(['A'], axis=1)
VLRROBA_list.to_excel(r'D:\合併完成excel.xlsx')

輸入路徑:D:\OBAtableau\PDMDtable_1M

In [6]:
df=VLRROBA_list.groupby(['YEAR','MONTH','time','PRODUCT_TYPE'])['SHIP_QTY','INSPECTION_QTY','Cost','YINSPECTION_QTY','YNG_QTY'].sum().reset_index()

<ipython-input-6-ac3c0ba3e4e2>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df=VLRROBA_list.groupby(['YEAR','MONTH','time','PRODUCT_TYPE'])['SHIP_QTY','INSPECTION_QTY','Cost','YINSPECTION_QTY','YNG_QTY'].sum().reset_index()

In [9]:
df['OBA/sorting rate']=df['INSPECTION_QTY']/df['SHIP_QTY']
df['OBA/sorting 不良率']=df['YNG_QTY']/df['YINSPECTION_QTY']
df.to_excel(r'D:\PD_Table.xlsx')

In [10]:
df

,YEAR,MONTH,time,PRODUCT_TYPE,SHIP_QTY,INSPECTION_QTY,Cost,YINSPECTION_QTY,YNG_QTY,OBA/sorting rate,OBA/sorting 不良率
0,2020.0,5.0,2020-05-01,AA-BD4,7.189447e+05,164311.0,6.488315e+06,123843.0,791.0,0.228545,0.006387
1,2020.0,5.0,2020-05-01,AUTO-BD5,3.578360e+05,79364.0,1.928448e+04,79364.0,184.0,0.221789,0.002318
2,2020.0,5.0,2020-05-01,CE,2.139408e+06,45527.0,1.847517e+05,45527.0,1179.0,0.021280,0.025897
3,2020.0,5.0,2020-05-01,IAVM,2.185833e+05,8369.0,3.992010e+04,8369.0,117.0,0.038287,0.013980
4,2020.0,5.0,2020-05-01,MONITOR,1.410520e+06,87735.0,7.855759e+05,39797.0,155.0,0.062200,0.003895
...,...,...,...,...,...,...,...,...,...,...,...
105,2021.0,3.0,2021-03-01,MP,4.651192e+06,667825.0,1.725089e+06,661478.0,2394.0,0.143581,0.003619
106,2021.0,3.0,2021-03-01,NB,4.652431e+06,164286.0,1.070984e+06,144702.0,4588.0,0.035312,0.031707
107,2021.0,3.0,2021-03-01,SET_TV,1.819207e+05,0.0,0.000000e+00,0.0,0.0,0.000000,NaN
108,2021.0,3.0,2021-03-01,TABLET,1.090676e+06,2477.0,5.683230e+04,2477.0,0.0,0.002271,0.000000
109,2021.0,3.0,2021-03-01,TV,2.873193e+06,19121.0,6.176004e+05,15648.0,11.0,0.006655,0.000703

In [13]:
OBAmean

  site  INSPECTION_QTY
0   AA       2272900.0
1   FS        788709.0
2  NGB       3537460.0
3   NJ       9686668.0
4   TN       6590482.0

In [ ]:
sis=pd.read_excel(r'D:\OBAtableau\2020實績\shipping_data_2020.xlsx')

In [ ]:
VLRROBA_list.groupby(['site'])('INSPECTION_QTY')
YEAR	MONTH	site	INSPECTION_QTY	Cost	YINSPECTION_QTY	NG_QTY	不良率